export const users = [
  {
    id: 1,
    name: "Alice",
    email: "alice@example.com",
    age: 30,
    occupation: "Software Engineer",
    city: "New York",
  },
  {
    id: 2,
    name: "Bob",
    email: "bob@example.com",
    age: 25,
    occupation: "Data Analyst",
    city: "San Francisco",
  },
  {
    id: 3,
    name: "Charlie",
    email: "charlie@example.com",
    age: 35,
    occupation: "Teacher",
    city: "Los Angeles",
  },
  {
    id: 4,
    name: "David",
    email: "david@example.com",
    age: 28,
    occupation: "Graphic Designer",
    city: "Chicago",
  },
  {
    id: 5,
    name: "Eva",
    email: "eva@example.com",
    age: 40,
    occupation: "Doctor",
    city: "Houston",
  },
  {
    id: 6,
    name: "Frank",
    email: "frank@example.com",
    age: 45,
    occupation: "Accountant",
    city: "Miami",
  },
  {
    id: 7,
    name: "Grace",
    email: "grace@example.com",
    age: 33,
    occupation: "Marketing Manager",
    city: "Seattle",
  },
  {
    id: 8,
    name: "Helen",
    email: "helen@example.com",
    age: 27,
    occupation: "Journalist",
    city: "Boston",
  },
  {
    id: 9,
    name: "Ian",
    email: "ian@example.com",
    age: 32,
    occupation: "Architect",
    city: "Austin",
  },
  {
    id: 10,
    name: "Jennifer",
    email: "jennifer@example.com",
    age: 38,
    occupation: "Lawyer",
    city: "Washington D.C.",
  },
];
